server:
  port: 8080
  servlet:
    context-path: /idp

# SAML IDP 核心配置
saml:
  idp:
    # IDP 实体ID（唯一标识）
    entity-id: https://idp.chukonu.com
    # 单点登录地址
    sso-url: http://localhost:8080/idp/saml/sso
    # 元数据暴露地址
    metadata-url: http://localhost:8080/idp/saml/metadata
    # 密钥库配置（用于签名SAML断言）
    keystore:
      path: classpath:keystore/idp.jks
      password: 123456
      key-alias: idp
      key-password: 123456
    # 断言有效期（秒）
    assertion-life-time: 3600
    trusted-sps:
      - entity-id: "https://sp.chukonu.com"
        acs-url: "http://localhost:8090/sp/saml/acs"
        slo-url: "https://mock-sp1.example.com/SAML2/SLO"
        encryption-cert-path: "classpath:certs/sp_public.crt" # 可选：用于加密断言的SP公钥

# Spring Security
spring:
  thymeleaf:
    cache: false