server:
  port: 8090
# context-path不用加
spring:
  security:
    saml2:
      relyingparty:
        registration:
          chukonu:
            entity-id: https://sp.chukonu.com
            assertingparty:
              metadata-uri: http://localhost:8080/idp/saml/metadata
